from typing import Protocol, runtime_checkable, Any
from universal_ai.domain.models import ModuleMetadata, ExecutionContext, Capability

@runtime_checkable
class BaseModule(Protocol):
    @property
    def metadata(self) -> ModuleMetadata: ...
    def required_capabilities(self) -> set[Capability]: ...
    async def execute(self, ctx: ExecutionContext, payload: dict[str, Any]) -> dict[str, Any]: ...
    async def health_check(self) -> bool: ...