import os
import zipfile
import subprocess
import sys
import tempfile

def L(*lines):
    """Helper to join lines safely, preventing any line-concatenation issues."""
    return "\n".join(lines)

ZIP_NAME = "universal_ai_platform.zip"

FILES = {
    "pyproject.toml": L(
        "[build-system]",
        "requires = [\"setuptools>=68.0\", \"wheel\"]",
        "build-backend = \"setuptools.build_meta\"",
        "[project]",
        "name = \"universal_ai_platform\"",
        "version = \"0.1.0\"",
        "requires-python = \">=3.12\"",
        "dependencies = [\"fastapi>=0.110.0\", \"uvicorn>=0.29.0\", \"pydantic>=2.6.0\", \"pydantic-settings>=2.2.0\"]",
        "[project.optional-dependencies]",
        "dev = [\"pytest>=8.1.0\", \"pytest-asyncio>=0.23.0\", \"httpx>=0.27.0\"]",
        "[tool.pytest.ini_options]",
        "asyncio_mode = \"auto\"",
        "testpaths = [\"tests\"]"
    ),
    "requirements.txt": L(
        "# Runtime dependencies only. Do NOT add test/dev packages here:",
        "# this file is installed into the production Docker image.",
        "# For test/dev tooling see requirements-dev.txt.",
        "fastapi>=0.110.0",
        "uvicorn>=0.29.0",
        "pydantic>=2.6.0",
        "pydantic-settings>=2.2.0"
    ),
    "requirements-dev.txt": L(
        "-r requirements.txt",
        "pytest>=8.1.0",
        "pytest-asyncio>=0.23.0",
        "httpx>=0.27.0"
    ),
    "Dockerfile": L(
        "FROM python:3.12-slim AS builder",
        "WORKDIR /app",
        "COPY requirements.txt .",
        "RUN pip install --no-cache-dir -r requirements.txt",
        "FROM python:3.12-slim AS runtime",
        "WORKDIR /app",
        "RUN groupadd -r appgroup && useradd -r -g appgroup appuser",
        "COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages",
        "COPY --from=builder /usr/local/bin /usr/local/bin",
        "COPY src ./src",
        "ENV PYTHONUNBUFFERED=1",
        "ENV PYTHONPATH=/app/src",
        "USER appuser",
        "EXPOSE 8000",
        "HEALTHCHECK CMD python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health')\" || exit 1",
        "CMD [\"uvicorn\", \"universal_ai.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]"
    ),
    ".dockerignore": L("__pycache__", "*.pyc", ".venv", "venv", "tests/"),
    ".gitignore": L("__pycache__/", "*.pyc", ".venv/", ".pytest_cache/", ".coverage"),
    "README.md": L(
        "# Universal Modular AI Platform",
        "Hexagonale Architektur, Pydantic v2, Python 3.12+.",
        "## Start",
        "pip install -r requirements-dev.txt  # runtime + test deps",
        "PYTHONPATH=src pytest -q",
        "PYTHONPATH=src uvicorn universal_ai.main:app --reload",
        "",
        "For a production install use `pip install -r requirements.txt` (runtime deps only)."
    ),
    "src/universal_ai/__init__.py": "",
    "src/universal_ai/main.py": L(
        "from universal_ai.api.app import create_app",
        "app = create_app()"
    ),
    "src/universal_ai/domain/__init__.py": "",
    "src/universal_ai/domain/exceptions.py": L(
        "class UniversalAIError(Exception):",
        "    def __init__(self, message: str, code: str):",
        "        super().__init__(message)",
        "        self.message, self.code = message, code",
        "class PolicyError(UniversalAIError):",
        "    def __init__(self, message: str): super().__init__(message, \"POLICY_ERROR\")",
        "class SandboxError(UniversalAIError):",
        "    def __init__(self, message: str): super().__init__(message, \"SANDBOX_ERROR\")",
        "class RoutingError(UniversalAIError):",
        "    def __init__(self, message: str): super().__init__(message, \"ROUTING_ERROR\")",
        "class ModuleError(UniversalAIError):",
        "    def __init__(self, message: str): super().__init__(message, \"MODULE_ERROR\")"
    ),
    "src/universal_ai/domain/models.py": L(
        "from dataclasses import dataclass, field",
        "from enum import Enum",
        "from typing import Any, FrozenSet, Optional",
        "from datetime import datetime",
        "",
        "class Capability(str, Enum):",
        "    LLM_INFERENCE = \"LLM_INFERENCE\"",
        "    CODE_EXECUTION = \"CODE_EXECUTION\"",
        "    MEMORY_READ = \"MEMORY_READ\"",
        "    TOOL_CALL = \"TOOL_CALL\"",
        "",
        "@dataclass(frozen=True)",
        "class TenantContext:",
        "    tenant_id: str",
        "    subject_id: str",        "    thread_id: str",
        "    request_id: str",
        "    correlation_id: str",
        "    permissions: FrozenSet[Capability]",
        "",
        "@dataclass(frozen=True)",
        "class ExecutionContext:",
        "    tenant_context: TenantContext",
        "    allowed_capabilities: FrozenSet[Capability]",
        "    allowed_tools: FrozenSet[str]",
        "    remaining_steps: int",
        "    remaining_tool_calls: int",
        "    timeout_seconds: float",
        "    is_cancelled: bool = False",
        "",
        "@dataclass(frozen=True)",
        "class Usage:",
        "    prompt_tokens: Optional[int] = None",
        "    completion_tokens: Optional[int] = None",
        "    total_tokens: Optional[int] = None",
        "",
        "@dataclass(frozen=True)",
        "class ModuleMetadata:",
        "    module_id: str",
        "    name: str",
        "    version: str",
        "    description: str",
        "    required_capabilities: FrozenSet[Capability]",
        "",
        "@dataclass(frozen=True)",
        "class PolicyDecision:",
        "    allowed: bool",
        "    reason: str",
        "    evaluated_capabilities: FrozenSet[Capability]",
        "",
        "@dataclass",
        "class DecisionTrace:",
        "    router: str",
        "    router_version: str",
        "    selected_module: str",
        "    candidate_modules: list[str]",
        "    matched_capabilities: list[Capability]",
        "    policy_decisions: list[PolicyDecision]",
        "    execution_steps: list[str]",
        "    timestamps: dict[str, datetime] = field(default_factory=dict)",
        "",
        "@dataclass(frozen=True)",
        "class AIProvenance:",
        "    generated: bool",
        "    generator_type: str",        "    model_id: Optional[str]",
        "    model_version: Optional[str]",
        "    generation_timestamp: datetime",
        "    content_type: str",
        "    machine_readable_marking: bool",
        "    human_visible_label_required: bool",
        "    human_visible_label_applied: bool",
        "",
        "@dataclass(frozen=True)",
        "class AuditEvent:",
        "    event_id: str",
        "    timestamp: datetime",
        "    request_id: str",
        "    tenant_id: str",
        "    actor: str",
        "    event_type: str",
        "    component: str",
        "    status: str",
        "    metadata: dict[str, Any]"
    ),
    "src/universal_ai/interfaces/__init__.py": "",
    "src/universal_ai/interfaces/modules.py": L(
        "from typing import Protocol, runtime_checkable, Any",
        "from universal_ai.domain.models import ModuleMetadata, ExecutionContext, Capability",
        "",
        "@runtime_checkable",
        "class BaseModule(Protocol):",
        "    @property",
        "    def metadata(self) -> ModuleMetadata: ...",
        "    def required_capabilities(self) -> set[Capability]: ...",
        "    async def execute(self, ctx: ExecutionContext, payload: dict[str, Any]) -> dict[str, Any]: ...",
        "    async def health_check(self) -> bool: ..."
    ),
    "src/universal_ai/interfaces/router.py": L(
        "from typing import Protocol, runtime_checkable",
        "from dataclasses import dataclass",
        "from universal_ai.domain.models import TenantContext, Capability",
        "",
        "@dataclass(frozen=True)",
        "class RouterDecision:",
        "    request_id: str",
        "    selected_module: str",
        "    confidence: float",
        "    alternatives: list[str]",
        "    matched_capabilities: list[Capability]",
        "    routing_reason: str",
        "",
        "@runtime_checkable",
        "class Router(Protocol):",
        "    async def route(self, ctx: TenantContext, payload: dict) -> RouterDecision: ..."    ),
    "src/universal_ai/interfaces/policies.py": L(
        "from typing import Protocol, runtime_checkable, Set",
        "from universal_ai.domain.models import TenantContext, Capability, PolicyDecision",
        "",
        "@runtime_checkable",
        "class PolicyEngine(Protocol):",
        "    async def evaluate(self, ctx: TenantContext, required_capabilities: Set[Capability]) -> PolicyDecision: ..."
    ),
    "src/universal_ai/interfaces/audit.py": L(
        "from typing import Protocol, runtime_checkable",
        "from universal_ai.domain.models import AuditEvent",
        "",
        "@runtime_checkable",
        "class AuditService(Protocol):",
        "    async def record(self, event: AuditEvent) -> None: ..."
    ),
    "src/universal_ai/interfaces/sandbox.py": L(
        "from typing import Protocol, runtime_checkable",
        "from dataclasses import dataclass",
        "from universal_ai.domain.models import ExecutionContext",
        "",
        "@dataclass(frozen=True)",
        "class SandboxResult:",
        "    stdout: str",
        "    stderr: str",
        "    exit_code: int",
        "",
        "@runtime_checkable",
        "class BaseSandbox(Protocol):",
        "    async def execute(self, ctx: ExecutionContext, code: str, language: str) -> SandboxResult: ..."
    ),
    "src/universal_ai/application/__init__.py": "",
    "src/universal_ai/application/module_registry.py": L(
        "from typing import List",
        "from universal_ai.interfaces.modules import BaseModule",
        "from universal_ai.domain.models import Capability",
        "from universal_ai.domain.exceptions import ModuleError",
        "",
        "class ModuleRegistry:",
        "    def __init__(self): self._modules: dict[str, BaseModule] = {}",
        "    def register(self, module: BaseModule) -> None:",
        "        if module.metadata.module_id in self._modules:",
        "            raise ModuleError(f\"Module {module.metadata.module_id} already registered\")",
        "        self._modules[module.metadata.module_id] = module",
        "    def get(self, module_id: str) -> BaseModule:",
        "        if module_id not in self._modules:",
        "            raise ModuleError(f\"Module {module_id} not found\")",
        "        return self._modules[module_id]",
        "    def list(self) -> List[BaseModule]: return list(self._modules.values())"    ),
    "src/universal_ai/application/router_service.py": L(
        "from typing import List",
        "from universal_ai.interfaces.router import Router, RouterDecision",
        "from universal_ai.domain.models import TenantContext, Capability",
        "from universal_ai.application.module_registry import ModuleRegistry",
        "from universal_ai.domain.exceptions import RoutingError",
        "",
        "class RuleBasedRouter(Router):",
        "    def __init__(self, registry: ModuleRegistry):",
        "        self.registry, self.version = registry, \"1.0.0\"",
        "    async def route(self, ctx: TenantContext, payload: dict) -> RouterDecision:",
        "        target = payload.get(\"target_module\", \"echo_module\")",
        "        candidates = [m.metadata.module_id for m in self.registry.list()]",
        "        if target not in candidates:",
        "            raise RoutingError(f\"Target module {target} not available\")",
        "        module = self.registry.get(target)",
        "        return RouterDecision(",
        "            request_id=ctx.request_id, selected_module=target, confidence=1.0,",
        "            alternatives=[c for c in candidates if c != target],",
        "            matched_capabilities=list(module.required_capabilities()),",
        "            routing_reason=\"Deterministic rule-based routing\"",
        "        )"
    ),
    "src/universal_ai/application/policy_service.py": L(
        "from typing import Set",
        "from universal_ai.interfaces.policies import PolicyEngine",
        "from universal_ai.domain.models import TenantContext, Capability, PolicyDecision",
        "",
        "class DefaultDenyPolicyEngine(PolicyEngine):",
        "    async def evaluate(self, ctx: TenantContext, required_capabilities: Set[Capability]) -> PolicyDecision:",
        "        missing = required_capabilities - ctx.permissions",
        "        if missing:",
        "            return PolicyDecision(False, f\"Missing permissions for: {', '.join(c.value for c in missing)}\", frozenset(required_capabilities))",
        "        return PolicyDecision(True, \"All capabilities granted\", frozenset(required_capabilities))"
    ),
    "src/universal_ai/application/orchestrator.py": L(
        "import uuid, hashlib, json",
        "from datetime import datetime, timezone",
        "from typing import Dict, Any, Set",
        "from universal_ai.domain.models import TenantContext, ExecutionContext, Usage, DecisionTrace, AIProvenance, AuditEvent, Capability",
        "from universal_ai.domain.exceptions import PolicyError",
        "from universal_ai.interfaces.router import Router",
        "from universal_ai.interfaces.policies import PolicyEngine",
        "from universal_ai.interfaces.audit import AuditService",
        "from universal_ai.application.module_registry import ModuleRegistry",
        "",
        "class Orchestrator:",
        "    def __init__(self, router: Router, registry: ModuleRegistry, policy_engine: PolicyEngine, audit_service: AuditService):",
        "        self.router, self.registry, self.policy_engine, self.audit_service = router, registry, policy_engine, audit_service",        "",
        "    async def handle(self, ctx: TenantContext, payload: Dict[str, Any]) -> Dict[str, Any]:",
        "        trace = DecisionTrace(self.router.__class__.__name__, getattr(self.router, 'version', 'unknown'), \"\", [], [], [], [], {\"start\": datetime.now(timezone.utc)})",
        "        try:",
        "            decision = await self.router.route(ctx, payload)",
        "            trace.selected_module, trace.candidate_modules, trace.matched_capabilities = decision.selected_module, decision.alternatives + [decision.selected_module], decision.matched_capabilities",
        "            trace.execution_steps.append(\"routed\")",
        "            ",
        "            module = self.registry.get(decision.selected_module)",
        "            required_caps: Set[Capability] = set(module.required_capabilities())",
        "            policy_decision = await self.policy_engine.evaluate(ctx, required_caps)",
        "            trace.policy_decisions.append(policy_decision)",
        "            trace.execution_steps.append(\"policy_evaluated\")",
        "            if not policy_decision.allowed: raise PolicyError(policy_decision.reason)",
        "",
        "            granted_caps = required_caps.intersection(ctx.permissions)",
        "            exec_ctx = ExecutionContext(ctx, frozenset(granted_caps), frozenset(), 10, 5, 30.0, False)",
        "            ",
        "            trace.execution_steps.append(\"executing_module\")",
        "            result = await module.execute(exec_ctx, payload)",
        "            trace.execution_steps.append(\"module_executed\")",
        "",
        "            is_generative = module.metadata.module_id not in [\"echo_module\"]",
        "            provenance = AIProvenance(is_generative, module.metadata.name, module.metadata.module_id if is_generative else None, module.metadata.version if is_generative else None, datetime.now(timezone.utc), \"text/plain\", True, not is_generative, False)",
        "",
        "            in_hash = hashlib.sha256(json.dumps(payload, sort_keys=True, separators=(',', ':')).encode('utf-8')).hexdigest()",
        "            out_hash = hashlib.sha256(json.dumps(result, sort_keys=True, separators=(',', ':')).encode('utf-8')).hexdigest()",
        "            ",
        "            audit_event = AuditEvent(str(uuid.uuid4()), datetime.now(timezone.utc), ctx.request_id, ctx.tenant_id, ctx.subject_id, \"MODULE_EXECUTION\", module.metadata.module_id, \"SUCCESS\", {\"input_hash\": in_hash, \"output_hash\": out_hash})",
        "            await self.audit_service.record(audit_event)",
        "            trace.execution_steps.append(\"audited\")",
        "            trace.timestamps[\"end\"] = datetime.now(timezone.utc)",
        "",
        "            return {\"request_id\": ctx.request_id, \"tenant_id\": ctx.tenant_id, \"thread_id\": ctx.thread_id, \"payload\": result, \"usage\": Usage(), \"provenance\": provenance, \"decision_trace\": trace, \"metadata\": {}}",
        "        except Exception as e:",
        "            trace.timestamps[\"end\"] = datetime.now(timezone.utc)",
        "            trace.execution_steps.append(f\"failed: {type(e).__name__}\")",
        "            await self.audit_service.record(AuditEvent(str(uuid.uuid4()), datetime.now(timezone.utc), ctx.request_id, ctx.tenant_id, ctx.subject_id, \"MODULE_EXECUTION\", trace.selected_module or \"unknown\", \"FAILURE\", {\"error_type\": type(e).__name__, \"error_code\": getattr(e, 'code', 'UNKNOWN')}))",
        "            raise"
    ),
    "src/universal_ai/infrastructure/__init__.py": "",
    "src/universal_ai/infrastructure/audit/__init__.py": "",
    "src/universal_ai/infrastructure/audit/in_memory.py": L(
        "from typing import List",
        "from universal_ai.interfaces.audit import AuditService",
        "from universal_ai.domain.models import AuditEvent",
        "",
        "class InMemoryAuditService(AuditService):",
        "    def __init__(self): self.events: List[AuditEvent] = []",
        "    async def record(self, event: AuditEvent) -> None: self.events.append(event)"    ),
    "src/universal_ai/infrastructure/sandbox/__init__.py": "",
    "src/universal_ai/infrastructure/sandbox/fake.py": L(
        "from universal_ai.interfaces.sandbox import BaseSandbox, SandboxResult",
        "from universal_ai.domain.models import ExecutionContext",
        "from universal_ai.domain.exceptions import SandboxError",
        "",
        "class FakeSandbox(BaseSandbox):",
        "    async def execute(self, ctx: ExecutionContext, code: str, language: str) -> SandboxResult:",
        "        raise SandboxError(\"Code execution is disabled in the current environment (FakeSandbox).\")"
    ),
    "src/universal_ai/modules/__init__.py": "",
    "src/universal_ai/modules/echo/__init__.py": L(
        "from typing import Set, Dict, Any",
        "from universal_ai.interfaces.modules import BaseModule",
        "from universal_ai.domain.models import ModuleMetadata, ExecutionContext, Capability",
        "",
        "class EchoModule(BaseModule):",
        "    @property",
        "    def metadata(self) -> ModuleMetadata:",
        "        return ModuleMetadata(\"echo_module\", \"Echo Module\", \"1.0.0\", \"Echoes input.\", frozenset())",
        "    def required_capabilities(self) -> Set[Capability]: return set(self.metadata.required_capabilities)",
        "    async def execute(self, ctx: ExecutionContext, payload: Dict[str, Any]) -> Dict[str, Any]:",
        "        return {\"echo\": payload.get(\"message\", \"No message\"), \"tenant_id\": ctx.tenant_context.tenant_id, \"request_id\": ctx.tenant_context.request_id}",
        "    async def health_check(self) -> bool: return True"
    ),
    "src/universal_ai/api/__init__.py": "",
    "src/universal_ai/api/schemas.py": L(
        "from pydantic import BaseModel, Field",
        "from typing import Any, Optional",
        "from universal_ai.domain.models import Usage, AIProvenance, DecisionTrace",
        "",
        "class RequestDTO(BaseModel):",
        "    message: str = Field(..., min_length=1, max_length=10000)",
        "    target_module: Optional[str] = \"echo_module\"",
        "    allowed_tools: list[str] = Field(default_factory=list)",
        "",
        "class ResponseDTO(BaseModel):",
        "    request_id: str",
        "    tenant_id: str",
        "    thread_id: str",
        "    payload: dict[str, Any]",
        "    usage: Usage",
        "    provenance: AIProvenance",
        "    decision_trace: DecisionTrace",
        "    metadata: dict[str, Any]"
    ),
    "src/universal_ai/api/deps.py": L(
        "from contextvars import ContextVar",
        "from fastapi import Request, HTTPException",        "from universal_ai.domain.models import TenantContext, Capability",
        "",
        "request_id_var: ContextVar[str] = ContextVar('request_id')",
        "correlation_id_var: ContextVar[str] = ContextVar('correlation_id')",
        "",
        "def get_tenant_context(request: Request) -> TenantContext:",
        "    req_id = request.headers.get(\"X-Request-ID\")",
        "    if not req_id: raise HTTPException(status_code=400, detail=\"Missing X-Request-ID header\")",
        "    request_id_var.set(req_id)",
        "    correlation_id_var.set(request.headers.get(\"X-Correlation-ID\", req_id))",
        "    tenant_id = request.headers.get(\"X-Tenant-ID\")",
        "    if not tenant_id: raise HTTPException(status_code=400, detail=\"Missing X-Tenant-ID header\")",
        "",
        "    # SECURITY: Permissions must NEVER be derived from client-supplied headers",
        "    # (X-Subject-ID, etc.) or any other value the caller controls, since that",
        "    # lets any client grant itself capabilities by spoofing the header.",
        "    # In production, replace this with capabilities extracted from a verified",
        "    # identity token (e.g. JWT claims validated against a trusted issuer) or",
        "    # looked up server-side from an authorization service. Default is deny-all.",
        "    permissions: set[Capability] = set()",
        "    subject_id = request.headers.get(\"X-Subject-ID\", \"anonymous\")",
        "",
        "    return TenantContext(tenant_id, subject_id, request.headers.get(\"X-Thread-ID\", \"default\"), req_id, request.headers.get(\"X-Correlation-ID\", req_id), frozenset(permissions))"
    ),
    "src/universal_ai/api/composition.py": L(
        "from universal_ai.application.orchestrator import Orchestrator",
        "from universal_ai.application.module_registry import ModuleRegistry",
        "from universal_ai.application.router_service import RuleBasedRouter",
        "from universal_ai.application.policy_service import DefaultDenyPolicyEngine",
        "from universal_ai.infrastructure.audit.in_memory import InMemoryAuditService",
        "from universal_ai.modules.echo import EchoModule",
        "",
        "_registry = ModuleRegistry()",
        "_registry.register(EchoModule())",
        "_audit_service = InMemoryAuditService()",
        "_policy_engine = DefaultDenyPolicyEngine()",
        "_router_service = RuleBasedRouter(_registry)",
        "",
        "orchestrator_instance = Orchestrator(_router_service, _registry, _policy_engine, _audit_service)",
        "",
        "def get_orchestrator() -> Orchestrator:",
        "    return orchestrator_instance"
    ),
    "src/universal_ai/api/routes.py": L(
        "from fastapi import APIRouter, Depends, HTTPException",
        "from universal_ai.api.schemas import RequestDTO, ResponseDTO",
        "from universal_ai.api.deps import get_tenant_context",
        "from universal_ai.domain.models import TenantContext",
        "from universal_ai.application.orchestrator import Orchestrator",
        "from universal_ai.domain.exceptions import UniversalAIError",
        "from universal_ai.api.composition import get_orchestrator",
        "",
        "router = APIRouter()",
        "",        "@router.get(\"/health\")",
        "async def health(): return {\"status\": \"ok\"}",
        "",
        "@router.get(\"/ready\")",
        "async def ready(): return {\"status\": \"ready\"}",
        "",
        "@router.get(\"/v1/modules\")",
        "async def get_modules(orchestrator: Orchestrator = Depends(get_orchestrator)):",
        "    return [{\"id\": m.metadata.module_id, \"name\": m.metadata.name} for m in orchestrator.registry.list()]",
        "",
        "@router.get(\"/v1/capabilities\")",
        "async def get_capabilities():",
        "    from universal_ai.domain.models import Capability",
        "    return [{\"value\": c.value} for c in Capability]",
        "",
        "@router.post(\"/v1/request\", response_model=ResponseDTO)",
        "async def handle_request(dto: RequestDTO, ctx: TenantContext = Depends(get_tenant_context), orchestrator: Orchestrator = Depends(get_orchestrator)):",
        "    try:",
        "        result = await orchestrator.handle(ctx, dto.model_dump())",
        "        return ResponseDTO(**result)",
        "    except UniversalAIError as e:",
        "        raise HTTPException(status_code=400, detail={\"code\": e.code, \"message\": e.message})",
        "    except Exception:",
        "        raise HTTPException(status_code=500, detail={\"code\": \"INTERNAL_ERROR\", \"message\": \"An internal error occurred\"})"
    ),
    "src/universal_ai/api/app.py": L(
        "from fastapi import FastAPI",
        "from universal_ai.api.routes import router",
        "",
        "def create_app() -> FastAPI:",
        "    app = FastAPI(title=\"Universal AI Platform\", version=\"0.1.0\")",
        "    app.include_router(router)",
        "    return app"
    ),
    "tests/__init__.py": "",
    "tests/architecture/__init__.py": "",
    "tests/architecture/test_dependencies.py": L(
        "import ast, os, pytest",
        "",
        "FORBIDDEN = {",
        "    \"domain\": [\"infrastructure\", \"api\", \"application\", \"interfaces\", \"modules\"],",
        "    \"interfaces\": [\"infrastructure\", \"api\", \"modules\"],",
        "    \"application\": [\"infrastructure\", \"api\", \"modules\"],",
        "}",
        "",
        "def test_architecture_boundaries():",
        "    violations = []",
        "    for layer, forbidden in FORBIDDEN.items():",
        "        layer_path = f\"src/universal_ai/{layer}\"",
        "        if not os.path.exists(layer_path): continue",        "        for root, _, files in os.walk(layer_path):",
        "            for file in files:",
        "                if file.endswith(\".py\"):",
        "                    filepath = os.path.join(root, file)",
        "                    with open(filepath, 'r') as f:",
        "                        tree = ast.parse(f.read())",
        "                    for node in ast.walk(tree):",
        "                        if isinstance(node, ast.Import):",
        "                            imports = [alias.name for alias in node.names]",
        "                        elif isinstance(node, ast.ImportFrom) and node.module:",
        "                            imports = [node.module]",
        "                        else: continue",
        "                        for imp in imports:",
        "                            for forb in forbidden:",
        "                                if f\"universal_ai.{forb}\" in imp or imp.startswith(f\"{forb}.\"):",
        "                                    violations.append(f\"{filepath} imports '{imp}'\")",
        "    assert not violations, \"Architecture violations:\\n\" + \"\\n\".join(violations)"
    ),
    "tests/security/__init__.py": "",
    "tests/security/test_tenant_isolation.py": L(
        "import pytest",
        "from universal_ai.domain.models import TenantContext, Capability",
        "from universal_ai.application.orchestrator import Orchestrator",
        "from universal_ai.application.module_registry import ModuleRegistry",
        "from universal_ai.application.router_service import RuleBasedRouter",
        "from universal_ai.application.policy_service import DefaultDenyPolicyEngine",
        "from universal_ai.infrastructure.audit.in_memory import InMemoryAuditService",
        "from universal_ai.modules.echo import EchoModule",
        "from universal_ai.domain.exceptions import PolicyError",
        "",
        "@pytest.fixture",
        "def orchestrator():",
        "    reg = ModuleRegistry()",
        "    reg.register(EchoModule())",
        "    return Orchestrator(RuleBasedRouter(reg), reg, DefaultDenyPolicyEngine(), InMemoryAuditService())",
        "",
        "@pytest.mark.asyncio",
        "async def test_tenant_context_propagation(orchestrator):",
        "    ctx = TenantContext(\"tenant_a\", \"user_1\", \"t1\", \"r1\", \"c1\", frozenset())",
        "    res = await orchestrator.handle(ctx, {\"message\": \"hello\", \"target_module\": \"echo_module\"})",
        "    assert res[\"tenant_id\"] == \"tenant_a\"",
        "    assert res[\"payload\"][\"echo\"] == \"hello\"",
        "",
        "@pytest.mark.asyncio",
        "async def test_policy_denies_missing_capabilities(orchestrator):",
        "    class FakeCode:",
        "        @property",
        "        def metadata(self):",
        "            from universal_ai.domain.models import ModuleMetadata",
        "            return ModuleMetadata(\"code_mod\", \"Code\", \"1.0\", \"\", frozenset({Capability.CODE_EXECUTION}))",        "        def required_capabilities(self): return {Capability.CODE_EXECUTION}",
        "        async def execute(self, ctx, payload): return {}",
        "        async def health_check(self): return True",
        "    orchestrator.registry.register(FakeCode())",
        "    ctx = TenantContext(\"tenant_b\", \"user_2\", \"t2\", \"r2\", \"c2\", frozenset())",
        "    with pytest.raises(PolicyError) as exc:",
        "        await orchestrator.handle(ctx, {\"message\": \"run\", \"target_module\": \"code_mod\"})",
        "    assert \"Missing permissions\" in str(exc.value)"
    ),
    "tests/unit/__init__.py": "",
    "tests/unit/test_orchestrator.py": L(
        "import pytest",
        "from universal_ai.domain.models import TenantContext",
        "from universal_ai.application.orchestrator import Orchestrator",
        "from universal_ai.application.module_registry import ModuleRegistry",
        "from universal_ai.application.router_service import RuleBasedRouter",
        "from universal_ai.application.policy_service import DefaultDenyPolicyEngine",
        "from universal_ai.infrastructure.audit.in_memory import InMemoryAuditService",
        "from universal_ai.modules.echo import EchoModule",
        "",
        "@pytest.fixture",
        "def orch():",
        "    reg = ModuleRegistry()",
        "    reg.register(EchoModule())",
        "    return Orchestrator(RuleBasedRouter(reg), reg, DefaultDenyPolicyEngine(), InMemoryAuditService())",
        "",
        "@pytest.mark.asyncio",
        "async def test_echo_end_to_end(orch):",
        "    ctx = TenantContext(\"t1\", \"s1\", \"th1\", \"req1\", \"cor1\", frozenset())",
        "    res = await orch.handle(ctx, {\"message\": \"test_payload\", \"target_module\": \"echo_module\"})",
        "    assert res[\"request_id\"] == \"req1\"",
        "    assert res[\"tenant_id\"] == \"t1\"",
        "    assert res[\"payload\"][\"echo\"] == \"test_payload\"",
        "    assert res[\"provenance\"].generated is False",
        "    assert \"audited\" in res[\"decision_trace\"].execution_steps"
    ),
    "tests/integration/__init__.py": "",
    "tests/integration/test_api.py": L(
        "import pytest",
        "from fastapi.testclient import TestClient",
        "from universal_ai.api.app import create_app",
        "",
        "@pytest.fixture",
        "def client(): return TestClient(create_app())",
        "",
        "def test_health(client):",
        "    assert client.get(\"/health\").status_code == 200",
        "",
        "def test_ready(client):",
        "    assert client.get(\"/ready\").status_code == 200",        "",
        "def test_get_modules(client):",
        "    res = client.get(\"/v1/modules\")",
        "    assert res.status_code == 200",
        "    assert any(m[\"id\"] == \"echo_module\" for m in res.json())",
        "",
        "def test_request_success(client):",
        "    headers = {\"X-Request-ID\": \"req-123\", \"X-Tenant-ID\": \"tenant-1\", \"X-Subject-ID\": \"user-1\"}",
        "    res = client.post(\"/v1/request\", json={\"message\": \"hello\", \"target_module\": \"echo_module\"}, headers=headers)",
        "    assert res.status_code == 200",
        "    data = res.json()",
        "    assert data[\"request_id\"] == \"req-123\"",
        "    assert data[\"payload\"][\"echo\"] == \"hello\"",
        "    assert data[\"provenance\"][\"generated\"] is False",
        "",
        "def test_request_missing_headers(client):",
        "    res = client.post(\"/v1/request\", json={\"message\": \"hello\"})",
        "    assert res.status_code == 400",
        "    assert \"Missing X-Request-ID\" in res.json()[\"detail\"]",
        "",
        "def test_request_unknown_module(client):",
        "    headers = {\"X-Request-ID\": \"req-456\", \"X-Tenant-ID\": \"tenant-1\"}",
        "    res = client.post(\"/v1/request\", json={\"message\": \"hello\", \"target_module\": \"fake\"}, headers=headers)",
        "    assert res.status_code == 400",
        "    assert \"ROUTING_ERROR\" in str(res.json()[\"detail\"])"
    )
}

def main():
    print(f"Erstelle {ZIP_NAME}...")
    with zipfile.ZipFile(ZIP_NAME, 'w', zipfile.ZIP_DEFLATED) as zf:
        for path, content in FILES.items():
            zf.writestr(path, content)
    
    print("Entpacke und validiere mit compileall...")
    with tempfile.TemporaryDirectory() as tmpdir:
        with zipfile.ZipFile(ZIP_NAME, 'r') as zf:
            zf.extractall(tmpdir)
        
        result = subprocess.run(
            [sys.executable, "-m", "compileall", "-q", tmpdir], 
            capture_output=True, 
            text=True
        )
        
        if result.returncode == 0:
            print("Erfolg: Alle Dateien sind syntaktisch valide. ZIP wurde erfolgreich validiert.")
        else:
            print("FEHLER: Syntaxprüfung fehlgeschlagen!")
            print(result.stderr)
            if os.path.exists(ZIP_NAME):
                os.remove(ZIP_NAME)
            sys.exit(1)

if __name__ == "__main__":
    main()
